apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: openshift101
spec:
  portal:
    registration:
      type: anonymous
    password: oslab
    ingress:
      hostname: "learn"
  workshops:
  - name: openshift101
    capacity: 10
    expires: 2h
    orphaned: 5m
